### ISSUE TITLE
Implement Configuration Steps for the Angular SDK

### ISSUE THREAD

**Issue by JanithGan** [asgardeo/asgardeo-auth-angular-sdk#11]
**Is your feature request related to a problem? Please describe.**

Developers must be able to properly configure the angular application to provide secure authentication with Asgardio / Identity server using the OIDC protocol. 

**Describe the solution you would prefer**

Adding support to provide configuration parameters (provided in the **[asgardio-js-oidc-sdk](https://github.com/asgardio/asgardio-js-oidc-sdk)**)  with a  separate configuration module. (_ASGARDIO_CONFIG_)

**Tasks**

- [x] Setting up Connection Parameters
- [ ] Setting up Storage Parameters
- [x] Setting up other OIDC Parameters
- [x] Setting up Redirect URIs
- [ ] Setting up Response Mode Parameters
