### ISSUE TITLE
Support to Get Tokens and Authentication State to Angular App

### ISSUE THREAD

**Issue by JanithGan** [asgardeo/asgardeo-auth-angular-sdk#14]
**Is your feature request related to a problem? Please describe.**

The application must be able to get access to tokens and the authentication state to perform tasks accordingly.

**Describe the solution you would prefer**

Following tasks are proposed.

**Tasks**

- [x] Obtain the access token 
- [x] Extract claims from the ID token 
- [x] Refresh the access token
- [x] Get Authentication State
