### ISSUE TITLE
Angular Authentication SDK Development

### ISSUE THREAD

**Issue by JanithGan** [asgardeo/asgardeo-auth-angular-sdk#4]
**Is your feature request related to a problem? Please describe.**

Currently, Asgardio / Identity Server doesn't have any client-side tools like SDKs or official guides on how to integrate angular application with the identity provider #3 

**Describe the solution you would prefer**

Develop a fully fledged **Angular Authentication SDK** to provide secure authentication for Angular applications with Asgardio / Identity Server.

**Tasks**

- [x] [Setting up Initial Project Skeleton for the Angular SDK](https://github.com/asgardio/asgardio-angular-oidc-sdk/issues/5)
- [x] [Implement Configuration Steps for the Angular SDK](https://github.com/asgardio/asgardio-angular-oidc-sdk/issues/11)
- [x] [Add Sign In and Sign Out Functionality to the Angular SDK ](https://github.com/asgardio/asgardio-angular-oidc-sdk/issues/12)
- [x] [Implement a Route Guard to Protect Angular App Pages](https://github.com/asgardio/asgardio-angular-oidc-sdk/issues/13)
- [x] [Support to Get Tokens and Authentication State to Angular Apps](https://github.com/asgardio/asgardio-angular-oidc-sdk/issues/14)
- [x] [Add Extracting User Information Functionality to Angular Apps](https://github.com/asgardio/asgardio-angular-oidc-sdk/issues/15)
- [x] [Implement a HTTP Interceptor to Call API Endpoints of the Identity Provider for Angular SDK](https://github.com/asgardio/asgardio-angular-oidc-sdk/issues/66)
- [x] [Add Support for Callback Functions for the Angular SDK](https://github.com/asgardeo/asgardeo-auth-angular-sdk/issues/69)
- [x] [Add Support for Custom Grant Types](https://github.com/asgardeo/asgardeo-auth-angular-sdk/issues/72)
