### ISSUE TITLE
Configure GitHub Actions for Automated Workflows

### ISSUE THREAD

**Issue by JanithGan** [asgardeo/asgardeo-auth-angular-sdk#6]
**Is your feature request related to a problem? Please describe.**

Automating workflows for the GitHub repository makes the development process much faster. Currently, this repository is not configured for automated workflows.

**Describe the solution you would prefer**

$subject

**Tasks**

- [x] [Actions Workflow to Automatically Build Pull Requests](https://github.com/asgardio/asgardio-angular-oidc-sdk/issues/8)
- [x] [Actions Workflow to Run CodeQL to Discover Vulnerabilities Across the Code-base ](https://github.com/asgardio/asgardio-angular-oidc-sdk/issues/9)
- [x] [ Actions Workflow to Automate the Process of Version Bumping and Release](https://github.com/asgardio/asgardio-angular-oidc-sdk/issues/10)
